modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/Lit-Fam/issues"
license="MIT"

[[mods]]
modId="litfam"
version="${file.jarVersion}"
displayName="It's Lit Fam"
displayURL="https://www.curseforge.com/minecraft/mc-mods/lit-fam"
authors="Mrbysco"
description='''
These entities are lit fam
'''
[[dependencies.litfam]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.litfam]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.60-beta,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config = "litfam.mixins.json"