modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Mrbysco/LitFam"
license="MIT"

[[mods]]
modId="litfam"
version="${file.jarVersion}"
displayName="It's Lit Fam"
displayURL="https://www.curseforge.com/minecraft/mc-mods/litfam"
authors="Mrbysco"
description='''
These entities are lit fam
'''
[[dependencies.litfam]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19)"
ordering="NONE"
side="BOTH"