modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/Mrbysco/Lit-Fam/issues"
license="MIT"

[[mods]]
modId="litfam"
version="${file.jarVersion}"
displayName="It's Lit Fam"
displayURL="https://www.curseforge.com/minecraft/mc-mods/lit-fam"
authors="Mrbysco"
description='''
These entities are lit fam
'''
[[dependencies.litfam]]
modId="minecraft"
mandatory=true
versionRange="[1.20.2,1.21)"
ordering="NONE"
side="BOTH"
[[mixins]]
config = "litfam.mixins.json"