modLoader="javafml"
loaderVersion="[37,)"
issueTrackerURL="https://github.com/Mrbysco/LitFam"
license="MIT"

[[mods]]
modId="litfam"
version="${file.jarVersion}"
displayName="It's Lit Fam"
displayURL="https://www.curseforge.com/minecraft/mc-mods/litfam"
authors="Mrbysco"
description='''
These entities are lit fam
'''
[[dependencies.litfam]]
modId="minecraft"
mandatory=true
versionRange="[1.17,1.18)"
ordering="NONE"
side="BOTH"
[[dependencies.litfam]]
modId="forge"
mandatory=true
versionRange="[37,38)"
ordering="NONE"
side="BOTH"